/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedJournalRouteImport } from './routes/_authed.journal'
import { Route as AuthedListsPrototypeRouteImport } from './routes/_authed.lists-prototype'
import { Route as AuthedJournalEntryIdRouteImport } from './routes/_authed.journal_.$entryId'
import { Route as AuthedJournalNewRouteImport } from './routes/_authed.journal_.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedJournalEntryIdEditRouteImport } from './routes/_authed.journal_.$entryId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedJournalRoute = AuthedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedListsPrototypeRoute = AuthedListsPrototypeRouteImport.update({
  id: '/lists-prototype',
  path: '/lists-prototype',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalEntryIdRoute = AuthedJournalEntryIdRouteImport.update({
  id: '/journal_/$entryId',
  path: '/journal/$entryId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJournalNewRoute = AuthedJournalNewRouteImport.update({
  id: '/journal_/new',
  path: '/journal/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedJournalEntryIdEditRoute =
  AuthedJournalEntryIdEditRouteImport.update({
    id: '/journal_/$entryId_/edit',
    path: '/journal/$entryId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/journal': typeof AuthedJournalRoute
  '/lists-prototype': typeof AuthedListsPrototypeRoute
  '/journal/$entryId': typeof AuthedJournalEntryIdRoute
  '/journal/new': typeof AuthedJournalNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/$entryId/edit': typeof AuthedJournalEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/journal': typeof AuthedJournalRoute
  '/lists-prototype': typeof AuthedListsPrototypeRoute
  '/journal/$entryId': typeof AuthedJournalEntryIdRoute
  '/journal/new': typeof AuthedJournalNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journal/$entryId/edit': typeof AuthedJournalEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/_authed/journal': typeof AuthedJournalRoute
  '/_authed/lists-prototype': typeof AuthedListsPrototypeRoute
  '/_authed/journal_/$entryId': typeof AuthedJournalEntryIdRoute
  '/_authed/journal_/new': typeof AuthedJournalNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/journal_/$entryId_/edit': typeof AuthedJournalEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/sign-in'
    | '/journal'
    | '/lists-prototype'
    | '/journal/$entryId'
    | '/journal/new'
    | '/api/auth/$'
    | '/journal/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/sign-in'
    | '/journal'
    | '/lists-prototype'
    | '/journal/$entryId'
    | '/journal/new'
    | '/api/auth/$'
    | '/journal/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/register'
    | '/sign-in'
    | '/_authed/journal'
    | '/_authed/lists-prototype'
    | '/_authed/journal_/$entryId'
    | '/_authed/journal_/new'
    | '/api/auth/$'
    | '/_authed/journal_/$entryId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/journal': {
      id: '/_authed/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthedJournalRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/lists-prototype': {
      id: '/_authed/lists-prototype'
      path: '/lists-prototype'
      fullPath: '/lists-prototype'
      preLoaderRoute: typeof AuthedListsPrototypeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal_/$entryId': {
      id: '/_authed/journal_/$entryId'
      path: '/journal/$entryId'
      fullPath: '/journal/$entryId'
      preLoaderRoute: typeof AuthedJournalEntryIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journal_/new': {
      id: '/_authed/journal_/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof AuthedJournalNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/journal_/$entryId_/edit': {
      id: '/_authed/journal_/$entryId_/edit'
      path: '/journal/$entryId/edit'
      fullPath: '/journal/$entryId/edit'
      preLoaderRoute: typeof AuthedJournalEntryIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedJournalRoute: typeof AuthedJournalRoute
  AuthedListsPrototypeRoute: typeof AuthedListsPrototypeRoute
  AuthedJournalEntryIdRoute: typeof AuthedJournalEntryIdRoute
  AuthedJournalNewRoute: typeof AuthedJournalNewRoute
  AuthedJournalEntryIdEditRoute: typeof AuthedJournalEntryIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedJournalRoute: AuthedJournalRoute,
  AuthedListsPrototypeRoute: AuthedListsPrototypeRoute,
  AuthedJournalEntryIdRoute: AuthedJournalEntryIdRoute,
  AuthedJournalNewRoute: AuthedJournalNewRoute,
  AuthedJournalEntryIdEditRoute: AuthedJournalEntryIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
